name: Build and release

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: build-release
  cancel-in-progress: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions: 
      contents: write # Required to create release

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - name: Update submodules
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git submodule foreach "git fetch origin master && git reset --hard FETCH_HEAD && git clean -df"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update submodules"
            git pull --rebase --empty=drop origin master
            git push origin HEAD:master
          fi

      - name: Install premake4
        run: |
          sudo apt-get update
          sudo apt-get install premake4 -y
      
      - name: Build
        run: |
          cd bootil/projects && premake4 gmake
          cd linux/gmake && make -j4
          cd ../../../../gmad && premake4 --bootil_lib="../bootil/lib/linux/gmake/" --bootil_inc="../bootil/include" gmake
          make -j4
          ./gmad_linux --help >/dev/null
      
      - name: Set release date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create dated release
        if: github.event_name == 'schedule'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "build-${{ env.RELEASE_DATE }}"
          name: "gmad_linux build (${{ env.RELEASE_DATE }})"
          prerelease: false
          generate_release_notes: false
          make_latest: false
          files: gmad/gmad_linux

      - name: Update latest release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          name: "gmad_linux build"
          prerelease: false
          generate_release_notes: false
          make_latest: true
          files: gmad/gmad_linux
